import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navegador from "../components/Navegador";
import About from "./about";
import Navegacao from "./navegacao";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navegador href="/estiloso" title="Estiloso" color="blue" />
        <Navegador href="/about" title="Sobre" color="red" />
        <Navegador href="/navegacao/" title="Navegacao #01" color="green" />
        <Navegador href="/cliente/123" title="Navegacao #02" color="purple" />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
